#!/usr/bin/env bash

execute_test() {
    while IFS= read -r line; do
        if [ ">" == "${line:0:1}" ]; then
            local val
            val=$(tr -d "> " <<< "$line")
            echo "$val"
            return 0
        fi
    done < <(printf '%s\n' "$@" | ./bin/calc)
    return 1
}

# Like execute_test but returns the LAST non-empty result (needed for res tests).
execute_test_last() {
    local last=""
    while IFS= read -r line; do
        if [ ">" == "${line:0:1}" ]; then
            local val
            val=$(tr -d "> " <<< "$line")
            [ -n "$val" ] && last=$val
        fi
    done < <(printf '%s\n' "$@" | ./bin/calc)
    echo "$last"
}

assert_test() {
    if [[ "$1" == "$2" ]]; then
        # test pass
        echo "[PASS] ${FUNCNAME[1]}"
        return 0
    fi
    # block execution
    echo "[FAIL] ${FUNCNAME[1]} Expected $2 got $1"
    exit 1
}

# ----------------- TEST DESCRIPTIONS -----------------

test_base10_sum(){
    local res=$(execute_test "9+1")
    assert_test $res "10"
}

test_base10_subtraction() {
    local res=$(execute_test "10-3")
    assert_test $res "7"
}

test_base10_multiplication() {
    local res=$(execute_test "3*4")
    assert_test $res "12"
}

test_base10_division() {
    local res=$(execute_test "10/3")
    assert_test $res "3"
}

test_base10_modulo() {
    local res=$(execute_test "10%3")
    assert_test $res "1"
}

test_base10_exponentiation() {
    local res=$(execute_test "2^8")
    assert_test $res "256"
}

test_base10_exponentiation_double_star() {
    local res=$(execute_test "2**8")
    assert_test $res "256"
}

test_base10_negative_operand() {
    local res=$(execute_test "-5+3")
    assert_test "$res" "-2"
}

test_base10_negative_result() {
    local res=$(execute_test "3-10")
    assert_test "$res" "-7"
}

test_base10_zero() {
    local res=$(execute_test "0+0")
    assert_test $res "0"
}

test_base16_sum() {
    local res=$(execute_test "ibase 10" "obase 16" "9+1")
    assert_test $res "A"
}

test_base16_input() {
    local res=$(execute_test "ibase 16" "obase 10" "A+5")
    assert_test $res "15"
}

test_base16_carry() {
    local res=$(execute_test "ibase 16" "obase 16" "F+1")
    assert_test $res "10"
}

test_base2_output() {
    local res=$(execute_test "ibase 10" "obase 2" "5+3")
    assert_test $res "00001000"
}

test_base2_input() {
    local res=$(execute_test "ibase 2" "obase 10" "1010+1")
    assert_test $res "11"
}

test_base8_output() {
    local res=$(execute_test "ibase 10" "obase 8" "8+1")
    assert_test $res "11"
}

test_base8_input() {
    local res=$(execute_test "ibase 8" "obase 10" "10+1")
    assert_test $res "9"
}

test_base_conversion_dec_to_hex() {
    local res=$(execute_test "ibase 10" "obase 16" "255")
    assert_test $res "FF"
}

test_base_conversion_hex_to_dec() {
    local res=$(execute_test "ibase 16" "obase 10" "FF")
    assert_test $res "255"
}

test_base_conversion_dec_to_bin() {
    local res=$(execute_test "ibase 10" "obase 2" "10")
    assert_test $res "00001010"
}

test_base2_negative_8bit() {
    local res=$(execute_test "ibase 10" "obase 2" "-2")
    assert_test $res "11111110"
}

test_base2_negative_min8bit() {
    local res=$(execute_test "ibase 10" "obase 2" "-128")
    assert_test $res "10000000"
}

test_base2_negative_16bit() {
    local res=$(execute_test "ibase 10" "obase 2" "-129")
    assert_test $res "1111111101111111"
}

test_base2_negative_result() {
    local res=$(execute_test "ibase 10" "obase 2" "3-10")
    assert_test $res "11111001"
}

test_float_addition() {
    local res=$(execute_test "ibase 10f" "obase 10f" "1.5+2.5")
    assert_test $res "4"
}

test_float_multiplication() {
    local res=$(execute_test "ibase 10f" "obase 10f" "1.5*2")
    assert_test $res "3"
}

test_float_division() {
    local res=$(execute_test "ibase 10f" "obase 10f" "10/4")
    assert_test $res "2.5"
}

test_float_exponentiation() {
    local res=$(execute_test "ibase 10f" "obase 10f" "2^10")
    assert_test $res "1024"
}

test_float_to_int_output() {
    local res=$(execute_test "ibase 10f" "obase 10" "3.9+0.1")
    assert_test $res "4"
}

test_res_basic() {
    local res=$(execute_test_last "1+1" "res+1")
    assert_test "$res" "3"
}

test_res_lhs() {
    local res=$(execute_test_last "5" "res*2")
    assert_test "$res" "10"
}

test_res_rhs() {
    local res=$(execute_test_last "5" "10+res")
    assert_test "$res" "15"
}

test_res_negative() {
    local res=$(execute_test_last "-3" "res+10")
    assert_test "$res" "7"
}

test_res_alone() {
    local res=$(execute_test_last "42" "res")
    assert_test "$res" "42"
}

test_res_float() {
    local res=$(execute_test_last "ibase 10f" "obase 10f" "1.5+1.5" "res*2")
    assert_test "$res" "6"
}

test_multi_addition() {
    local res=$(execute_test "10+10+10")
    assert_test $res "30"
}

test_multi_mixed_precedence() {
    local res=$(execute_test "2+3*4")
    assert_test $res "14"
}

test_multi_parens_override_precedence() {
    local res=$(execute_test "(2+3)*4")
    assert_test $res "20"
}

test_multi_nested_parens() {
    local res=$(execute_test "((2+3)*2+1)*3")
    assert_test $res "33"
}

test_multi_power_right_assoc() {
    local res=$(execute_test "2^3^2")
    assert_test $res "512"
}

test_multi_complex_expr() {
    local res=$(execute_test "10/2+3*4-1")
    assert_test $res "16"
}

test_multi_unary_minus_in_expr() {
    local res=$(execute_test "-2*3+10")
    assert_test $res "4"
}

test_multi_float_precedence() {
    local res=$(execute_test "ibase 10f" "obase 10f" "1.5+2.5*2")
    assert_test $res "6.5"
}

test_multi_float_parens() {
    local res=$(execute_test "ibase 10f" "obase 10f" "(1.5+2.5)*2")
    assert_test $res "8"
}

test_multi_res_in_expr() {
    local res=$(execute_test_last "3" "res*2+1")
    assert_test $res "7"
}

# ----------------- TEST EXECUTIONS -----------------
test_base10_sum
test_base10_subtraction
test_base10_multiplication
test_base10_division
test_base10_modulo
test_base10_exponentiation
test_base10_exponentiation_double_star
test_base10_negative_operand
test_base10_negative_result
test_base10_zero
test_base16_sum
test_base16_input
test_base16_carry
test_base2_output
test_base2_input
test_base8_output
test_base8_input
test_base_conversion_dec_to_hex
test_base_conversion_hex_to_dec
test_base_conversion_dec_to_bin
test_base2_negative_8bit
test_base2_negative_min8bit
test_base2_negative_16bit
test_base2_negative_result
test_float_addition
test_float_multiplication
test_float_division
test_float_exponentiation
test_float_to_int_output
test_res_basic
test_res_lhs
test_res_rhs
test_res_negative
test_res_alone
test_res_float
test_multi_addition
test_multi_mixed_precedence
test_multi_parens_override_precedence
test_multi_nested_parens
test_multi_power_right_assoc
test_multi_complex_expr
test_multi_unary_minus_in_expr
test_multi_float_precedence
test_multi_float_parens
test_multi_res_in_expr
